### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by haesleinhuepf** [BioDepot/fiji-clij#3]
Hi @kayeeyeung @evan3334 and @rgschmitz1 ,

that's a super amazing project you're working on here! I'm glad to see that clij is useful.

May I make a small suggestion. If people wanted to use your project for their science, they need the one way or another make a copy of it. Therefore, a copyright statement (license file) would be good in your project. Otherwise it's kind-of illegal to copy your work. And with a license file you can also make sure you're not liable if others do wrong things with your tools.

https://choosealicense.com

Thanks!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Also another minor issue: Some files in [this folder](https://github.com/BioDepot/fiji-clij/tree/master/clij_files) may originate from [this repository](https://github.com/clij/clij-benchmarking) which is [BSD](https://en.m.wikipedia.org/wiki/BSD_licenses) licensed. This means, you're ok to copy it, but you should also copy the license file from the source to make sure the original copyright holders are not forgotten. Read more in our license:

https://github.com/clij/clij-benchmarking/blob/master/license.txt

**Comment by kayeeyeung** [comment]
Hi @haesleinhuepf 

Thank you for your feedback. We will add licensing information to our repo. 
We are excited that you find our project interesting. Can I invite you to test drive our tools and provide feedback in our usability study?

This should take ~30 minutes and would let you try our tools on AWS.

We are expanding the scope of our work from genomics to bioimage data, and would greatly appreciate input from the bioimage community to guide our future work.

Thanks
Ka Yee


> Hi @kayeeyeung @evan3334 and @rgschmitz1 ,
> 
> that's a super amazing project you're working on here! I'm glad to see that clij is useful.
> 
> May I make a small suggestion. If people wanted to use your project for their science, they need the one way or another make a copy of it. Therefore, a copyright statement (license file) would be good in your project. Otherwise it's kind-of illegal to copy your work. And with a license file you can also make sure you're not liable if others do wrong things with your tools.
> 
> https://choosealicense.com
> 
> Thanks!
> 
> Best, Robert
